import { Aircraft, EmptyLeg } from "./types";

export const aircraftFleet: Aircraft[] = [
  {
    id: "1",
    name: "Citation CJ3+",
    type: "Light Jet",
    capacity: 7,
    maxRange: 2040,
    cruiseSpeed: 464,
    hourlyRate: 3500,
    images: ["/images/aircraft/aircraft-1.png"],
    features: ["WiFi", "Refreshment Center", "Leather Seating"],
    available: true,
  },
  {
    id: "2",
    name: "Hawker 850XP",
    type: "Mid-Size Jet",
    capacity: 8,
    maxRange: 2642,
    cruiseSpeed: 446,
    hourlyRate: 4200,
    images: ["/images/aircraft/aircraft-2.png"],
    features: ["Full Galley", "Entertainment System", "Spacious Cabin"],
    available: true,
  },
  {
    id: "3",
    name: "Gulfstream G450",
    type: "Heavy Jet",
    capacity: 14,
    maxRange: 4350,
    cruiseSpeed: 528,
    hourlyRate: 6800,
    images: ["/images/aircraft/aircraft-3.png"],
    features: ["Bedroom", "Full Kitchen", "Conference Area"],
    available: true,
  },
];

export const emptyLegsDeals: EmptyLeg[] = [
  {
    id: "1",
    aircraft: aircraftFleet[0],
    from: "New York (TEB)",
    to: "Miami (MIA)",
    departureDate: "2025-02-15",
    departureTime: "09:00",
    duration: "2h 45m",
    originalPrice: 8500,
    discountedPrice: 5500,
    discount: 35,
    seats: 6,
  },
  {
    id: "2",
    aircraft: aircraftFleet[1],
    from: "Los Angeles (LAX)",
    to: "Las Vegas (LAS)",
    departureDate: "2025-02-18",
    departureTime: "14:30",
    duration: "1h 20m",
    originalPrice: 6200,
    discountedPrice: 3800,
    discount: 40,
    seats: 7,
  },
  {
    id: "3",
    aircraft: aircraftFleet[2],
    from: "Chicago (MDW)",
    to: "Denver (DEN)",
    departureDate: "2025-02-20",
    departureTime: "11:15",
    duration: "2h 10m",
    originalPrice: 12000,
    discountedPrice: 7200,
    discount: 40,
    seats: 12,
  },
];

export const popularDestinations = [
  "New York (TEB)",
  "Los Angeles (LAX)",
  "Miami (MIA)",
  "Las Vegas (LAS)",
  "Chicago (MDW)",
  "Denver (DEN)",
  "Dallas (DAL)",
  "Boston (BOS)",
];
